# Generated by Django 3.1.7 on 2021-03-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_order_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
