# Generated by Django 3.1.7 on 2021-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_order_complete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='assign_time',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
